### ISSUE TITLE
NestedRecovery save keys in uppercase format

### ISSUE THREAD

**Issue by Halfeez92** [AloneLiberty/FlipperNested#10]
I have found an issue, that when the recovery script found the keys, it will be saved in the user dictionary in UPPERCASE format. But upon re-scanning the NFC card again, it will be missing a few nonces despite of the keys have already been found.

The solution I did is to manually edit the keys in user dictionary to be saved in lowercase format. Then the Flipper can read all the NFC nonces completely. Maybe you can change the recovery script to save the keys in lowercase format. Thank you.

**Comment by AloneLiberty** [comment]
I don't think this is bug from my side. Can you share FULL tag dump and both (working in lowercase and not working in uppercase) dictionaries? Also specify your Flipper Zero firmware version. If you can't share them here, you can contact me in Telegram

**Comment by JakobPetersson** [comment]
I can confirm experiencing this (Or something very similar).

Release 0.87.0

Scenario: Mifare Classic 1K, Sector 0, Key A and B unknown
- Recovered B-key using Mfkey32, added to user dictionary.
- Could read with 31/32 keys found (**Repeatedly** 10+ times). (**Sector 0 A-key** being the missing key)
- Performed nested  attack, recovered sector 0 A-key, added to user dictionary.
- Could still only read with 31/32 keys found (**Repeatedly** 10+ times). (**Sector 0 B-key** being the missing key this time)
- Could verify the key list in Flipper GUI. Both keys added. B-key lower case, A-key upper case.
- Manually opened user dictionary on computer, changed both keys to upper case.
- Could read with 32/32 keys found (Repeatedly 10+ times).
- Manually opened user dictionary on computer, changed both keys to lower case.
- Could read with 32/32 keys found (Repeatedly 10+ times).
- Manually opened user dictionary on computer, changed one key to lower case, one to upper case.
- Could read with 32/32 keys found (Repeatedly 10+ times).

So for me the case doesn't seemed to matter after the key file has been poked by a computer.
Maybe the file got "corrupted" somehow?

**Comment by AloneLiberty** [comment]
Can you reproduce nested writing invalid key? If yes, can you provide corruped keys file and full tag dump?

**Comment by AloneLiberty** [comment]
Closing due to no response
