### ISSUE TITLE
Are there plans to implement Darkside?

### ISSUE THREAD

**Issue by DeNcHiK3713** [AloneLiberty/FlipperNested#13]
Maybe there are some developments?
Maybe the implementation in Chameleon Ultra will help
https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/firmware/application/src/rfid/reader/hf/mf1_toolbox.c#L259
Here is a description of the attack itself https://eprint.iacr.org/2009/137.pdf
I would like to try to implement this myself, but I don't have experience and knowledge of C for development, so it will take a long time.

**Comment by AloneLiberty** [comment]
Please read FAQ, already contains information about it. I've already looked into Chameleon Ultra code, but without deep modification and (probably) new approach on running on Flipper Zero it's impossible. I don't have free time to waste on such unimportant (?) thing.

**Comment by DeNcHiK3713** [comment]
Thanks for your reply. I have several cards for which the key is unknown and I cannot use the Detect Reader attack on them. Then, I think, it makes sense to close this issue until such time as work begins on it. All in all, I don't really need it for now. In any case, I'll try to figure it out myself when I have time.
I also want to say thank you for such a useful utility and the implementation of nested attacks.

**Comment by noproto** [comment]
FYA - I'm beginning development of this today @DeNcHiK3713 at https://github.com/noproto/FlipperNested.
