### ISSUE TITLE
 having trouble running "FlipperNested" in Terminal.

### ISSUE THREAD

**Issue by TomShook1** [AloneLiberty/FlipperNested#18]
Hello,
I am having trouble running "FlipperNested" in Terminal.
I typed: python -m FlipperNested
and nothing happens.
No error message saying that the file does not exist, nothing.
Wondering if someone could help.

Update:
when the Flipper is not plugged in and I try to execute, the terminal spits out "Flipper missing" message.
when qFlipper is open (and flipper is connected) and I try to execute, it gives me a permission error.
Please help
Thanks.
(I'm VERY new to this)

**Comment by AloneLiberty** [comment]
> when the Flipper is not plugged in and I try to execute, the terminal spits out "Flipper missing" message.
> when qFlipper is open (and flipper is connected) and I try to execute, it gives me a permission error.

Maybe because you need to connect Flipper and don't open qFlipper?
