### ISSUE TITLE
Mifare Classic 4k one key not enough

### ISSUE THREAD

**Issue by Allperino** [AloneLiberty/FlipperNested#20]
I tried to read Mifare Classic 4k card with Flipper main app using dictionary and it found just 1 key (out of 80) and 1 sector (out of 40). I tried to run FlipperNested on the same card but got "No keys found" error.

- Does FlipperNested support 4K cards?
- Do I need more than one key to run Nested attack? (get some more via "Detect reader" and Mfkey32)

Or is there another problem?

**Comment by AloneLiberty** [comment]
Are you sure you saved card after scanning it with NFC app (with 1 found key)?

**Comment by Allperino** [comment]
Yes. If the file helps: 
[mifare4k.nfc.txt](https://github.com/AloneLiberty/FlipperNested/files/12536895/mifare4k.nfc.txt)

**Comment by AloneLiberty** [comment]
Are you on latest version of OFW? Do you have /ext/nfc/.cache/9AB2E174.keys file?

**Comment by Allperino** [comment]
I am on 0.88.1 of Rougemaster. Didnt update in a while. Will update and try again.
I found the keys file:
[9AB2E184.keys.txt](https://github.com/AloneLiberty/FlipperNested/files/12536945/9AB2E184.keys.txt)

**Comment by AloneLiberty** [comment]
Try on latest version of OFW and reply with results (scan, save dump and run)

**Comment by Allperino** [comment]
Yeah I should have tried that in the first place. My bad. Works now, thanks 👍
