### ISSUE TITLE
Set custom block for tag detection

### ISSUE THREAD

**Issue by Matthew78917** [AloneLiberty/FlipperNested#4]
_Originally posted by @AloneLiberty in https://github.com/AloneLiberty/FlipperNested/discussions/3#discussioncomment-5797792_

**Comment by Matthew78917** [comment]
_Originally posted by @AloneLiberty in https://github.com/AloneLiberty/FlipperNested/discussions/3#discussioncomment-5797792_

**Comment by AloneLiberty** [comment]
Should also include "Force/always Hard Nested" setting
